# Generated by Django 4.1.6 on 2023-08-05 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_course', to='course.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_topic', to='course.topic'),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='course_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
