# Generated by Django 4.2.3 on 2023-11-12 20:16

import course.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, choices=[('Advice', 'advice'), ('Development', 'development')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.CharField(blank=True, choices=[('Beginner', 'beginner'), ('Intermediate', 'intermediate'), ('Advanced', 'advanced')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/', validators=[course.validators.validate_file_size]),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
