# Generated by Django 4.2.3 on 2023-10-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_host_alter_file_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(choices=[('Beginner', 'beginner'), ('Intermediate', 'intermediate'), ('Advanced', 'advanced')], max_length=50),
        ),
    ]
