# Generated by Django 4.1.6 on 2023-08-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_tag_remove_course_max_user_num_course_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
