# Generated by Django 4.1.6 on 2023-08-15 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_end_date_alter_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.file'),
        ),
    ]
