# Generated by Django 4.2.3 on 2023-08-16 02:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_content_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
