# Generated by Django 4.1.6 on 2023-09-15 12:12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_content_body_alter_course_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='publication',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
