# Generated by Django 4.1.6 on 2023-09-15 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_publication_alter_course_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_topic', to='course.topic'),
        ),
    ]
