# Generated by Django 4.1.6 on 2023-09-17 14:58
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
