# Generated by Django 3.2.8 on 2023-09-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20230918_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_description',
            new_name='description',
        ),
    ]
