# Generated by Django 3.2.8 on 2023-09-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='publication',
            field=models.BooleanField(default=False),
        ),
    ]
