# Generated by Django 4.1.6 on 2023-07-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selected_answer',
            name='question',
        ),
    ]
