# Generated by Django 4.1.6 on 2023-07-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_questions',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.TimeField(help_text='duration of the quiz in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='required_score',
            field=models.IntegerField(help_text='required score in %', null=True),
        ),
    ]
