# Generated by Django 4.2.3 on 2023-11-06 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Average_score',
        ),
    ]
