# Generated by Django 4.1.6 on 2023-08-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='complete',
            field=models.ManyToManyField(related_name='quiz_comp', to='quiz.quiz_completion'),
        ),
    ]
