# Generated by Django 4.2.3 on 2023-09-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='publication',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
