# Generated by Django 4.2.3 on 2023-10-02 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_selected_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='average_score',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='average_score_ques', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='completed_quiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete_quiz_quiz', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='completed_quiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete_quiz_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='selected_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sel_answer_ques', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='selected_answer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sel_answer_quiz', to='quiz.completed_quiz'),
        ),
        migrations.AlterField(
            model_name='selected_answer',
            name='selected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sel_answer_ans', to='quiz.answer'),
        ),
        migrations.AlterField(
            model_name='selected_answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sel_answer_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
