# Generated by Django 4.2.3 on 2023-09-21 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_publication_alter_quiz_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='complete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_comp', to='quiz.quiz_completion'),
        ),
    ]
