# Generated by Django 4.1.6 on 2023-08-05 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_average_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='average_score',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='average_score_quiz', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_quiz', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_host', to=settings.AUTH_USER_MODEL),
        ),
    ]
