# Generated by Django 4.2.3 on 2023-09-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_content_publication'),
        ('quiz', '0005_quiz_created_at_quiz_end_date_quiz_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='complete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_comp', to='quiz.quiz_completion'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_content', to='course.content'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_course', to='course.course'),
        ),
    ]
