# Generated by Django 4.2.3 on 2023-09-24 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0006_alter_answer_question_alter_quiz_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='average_score',
            name='user',
            field=models.ManyToManyField(related_name='average_score_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
