# Generated by Django 4.1.6 on 2023-08-15 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_tag_remove_course_max_user_num_course_end_date_and_more'),
        ('quiz', '0007_quiz_completed_quiz_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_content', to='course.content'),
        ),
    ]
