# Generated by Django 4.1.6 on 2023-08-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quiz_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='explanation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='completed',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.TimeField(blank=True, help_text='duration of the quiz in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='required_score',
            field=models.IntegerField(blank=True, help_text='required score in %', null=True),
        ),
    ]
