# Generated by Django 4.1.6 on 2023-08-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_explanation_alter_quiz_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='explanation',
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
