# Generated by Django 4.2.3 on 2023-10-29 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follower', '0002_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='chatroom_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
