# Generated by Django 4.2.3 on 2023-10-29 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follower', '0003_chatroom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_host', to=settings.AUTH_USER_MODEL),
        ),
    ]
