# Generated by Django 4.2.3 on 2023-11-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0006_notification_is_read_alter_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationlist',
            name='notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='list',
            field=models.ManyToManyField(related_name='list_notification', to='follower.notificationlist'),
        ),
    ]
