# Generated by Django 4.2.3 on 2023-11-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0007_remove_notificationlist_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='list',
        ),
        migrations.AddField(
            model_name='notificationlist',
            name='notification',
            field=models.ManyToManyField(related_name='list_notification', to='follower.notification'),
        ),
    ]
