# Generated by Django 4.2.3 on 2023-11-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_completion_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='badge',
        ),
        migrations.AddField(
            model_name='profile',
            name='badge',
            field=models.ManyToManyField(blank=True, to='user.badge'),
        ),
    ]
