# Generated by Django 4.1.6 on 2023-08-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_followrequest_followlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='FollowList',
        ),
        migrations.DeleteModel(
            name='FollowRequest',
        ),
    ]
