# Generated by Django 4.2.3 on 2023-10-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
